# SearXNG settings

use_default_settings: true

server:
  port: 8888
  bind_address: "127.0.0.1"
  secret_key: "ea5722cc5de5c18ef471897f5fcc5fae9e4b7206307e9659a3d2a8aff875fd57"
  base_url: false

ui:
  static_path: ""
  templates_path: ""
  query_in_title: true
  infinite_scroll: false
  center_alignment: true
  default_locale: "en"
  theme: simple

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en-US"
  formats:
    - html
    - json

engines:
  - name: google
    engine: google
    shortcut: g
    use_mobile_ui: true
    timeout: 3.0

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    timeout: 3.0

  - name: wikipedia
    engine: wikipedia
    shortcut: w
    timeout: 2.0

  - name: wikidata
    engine: wikidata
    shortcut: wd
    timeout: 2.0

  - name: bing
    engine: bing
    shortcut: b
    disabled: false
    timeout: 3.0

enabled_plugins:
  - 'Hash plugin'
  - 'Self Information'
  - 'Tracker URL eliminator'
  - 'Aisearch'
